-- STRING & NUMBER FUNCTION MYSQL :
-- NUMBER FUNCTION
SELECT 10, 10, 10 * (10 + 2) AS hasil;
SELECT AVG(quantity) FROM products;
SELECT ABS(-45);
SELECT CEIL(25.44);
SELECT FLOOR(25.44);
SELECT COUNT(id) AS ProductID FROM products;
SELECT GREATEST(3, 12, 34, 12, 25);
SELECT LEAST(31, 12, 34, 8, 25);
SELECT MAX(quantity) AS LargePrice FROM products;
SELECT MIN(quantity) AS LargePrice FROM products;
SELECT POW(3, 3);
SELECT MOD(18, 4);
SELECT 10 DIV 3;
SELECT SQRT(8);
SELECT SUM(price) FROM products;
SELECT POWER(4, 3);
SELECT id, name, price FROM products WHERE price DIV 1000 > 10;
SELECT id, name, price DIV 100 AS 'Price in K' FROM products;
SELECT price, ROUND(price, 2) AS RoundPrice FROM products;

-- STRING FUNCTION
SELECT email, CHAR_LENGTH(email) AS namaCustomer FROM customers;
SELECT * FROM customers;
SELECT CONCAT(first_name, last_name) AS NamaLengkap FROM customers;
SELECT CONCAT_WS("-", "SQL", "Tutorial", "is", "fun!") AS ConcatenatedString;
SELECT FIELD(5, 0, 1, 2, 3, 4, 5);
SELECT FIND_IN_SET("r", "m,y,s,q,l,q,u,e,r,y");
SELECT FORMAT(122425434, 2);
SELECT INSERT("W3Schools.com", 1, 9, "Example");
SELECT INSTR("W3Schools.com", "l") AS MatchPosition;
SELECT LCASE("SQL Tutorial is FUN!") AS LowercaseText;
SELECT LCASE(name) AS nama FROM products;
SELECT LEFT("SQL Tutorial", 3) AS ExtractString;
SELECT LEFT(name, 5) FROM  products;
SELECT LENGTH("SQL Tutorial") AS LengthOfString;
SELECT LENGTH(name) FROM products;
SELECT LOCATE(".c", "W3Schools.com") AS MatchPosition;
SELECT LOCATE("com", "W3Schools.com") AS MatchPosition;
SELECT LOWER("SQL Tutorial is FUN!");
SELECT LOWER(name) FROM products;
SELECT LPAD("SQL Tutorial", 18, "A-B-C-");
SELECT LPAD(name, 20, "A-") FROM products;
SELECT LTRIM("      SQL Tutorial") AS LeftTrimmedString;
SELECT MID("SQLTutorial", 4, 5) AS ExtractString;	
SELECT POSITION("com" IN "W3Schools.com") AS MatchPosition;
SELECT POSITION('a' IN name) FROM products;
SELECT REPEAT("SQL Tutorial - ", 3) AS REPEATFUNCTION;
SELECT REPEAT(category, 3) FROM products;
SELECT REPLACE("SQL Tutorial", "SQL", "HTML");
SELECT REPLACE("XYZ FGH XYZ", "X", "m");
SELECT REVERSE(category) FROM products;
SELECT RIGHT(name, 12) FROM products;
SELECT RPAD(name, 30, '-add') FROM products;
SELECT RTRIM("SQL Tutorial          ") AS RightTrimmedString;
SELECT SUBSTR("SQLTutorial", 4, 5) AS ExtractString;
SELECT SUBSTR("SQLTutorial" FROM 4 FOR 5) AS ExtractString;
SELECT SUBSTRING("SQLTutorial" FROM 4 FOR 5) AS ExtractString;
SELECT SUBSTRING_INDEX("www.w3schools.com", ".", 2);
SELECT TRIM("    SQL Tutorial    ") AS TrimmedString;
SELECT UCASE(name) AS nama FROM products;
SELECT UPPER("SQL Tutorial is FUN!");